### ISSUE TITLE
Compilation issues with HDF5

### ISSUE THREAD

**Issue by akashdhruv** [akashdhruv/Boiling-Simulations#1]
Let's track the issue here. Emails are hard to archive for future purposes.

**Comment by akashdhruv** [comment]
Do the following,

Switch to main branch:
`git checkout main`

Pull latest changes:
`git pull`

Update jobrunner:
`pip install --upgrade PyJobRunner`

Run
`jobrunner setup software`
`jobrunner archive software`

Create another branch and push `jobnode.archive`

**Comment by difan0224** [comment]
Done. Please check.

**Comment by akashdhruv** [comment]
HDF5 failing in configure stage.
